datapath = '/Users/timowendner/Programming/MultiHeadCNN/data'
classes = 10        # number of classes to predict
in_channels = 3     # number of channels in the image (3 for rgb)
lr = 0.0001         # learning rate
batch_size = 16     # batch size
num_epochs = 100    # number of epochs to train

# convolutional layers
# a layer consists of a simple convolution that changes the channels,
# followed by two residual blocks
conv_layers = [128, 256, 256, 256, 256]

# layer specification of the linar layers
linear_layers = [256, 256, 128]