datapath = '/Users/timowendner/Programming/MultiHeadCNN/data'

# training parameters
lr = 0.0001
batch_size = 16
num_epochs = 100
data_on_device = false

# task specification
classes = 10
input_shape = [3, 32, 32]

# model specification
model_type = 'cnn'
kernel = 3
block_size = 2
block_count = 4
dropout = 0.2
padding = 1
conv_layers = [32, 64, 32]
linear_layers = [64, 64, 32]